-- DELETE FROM table_name WHERE condition;
DELETE FROM members_hobby 
WHERE MEMBERS_ID = 'M-02';
DELETE FROM members_hobby 
WHERE MEMBERS_ID = 'M-03';
DELETE FROM members_hobby 
WHERE MEMBERS_ID = 'M-04';
DELETE FROM members_hobby 
WHERE MEMBERS_ID = 'M-05';


DELETE FROM membewrs_login
WHERE MEMBERS_ID = 'M-02';
DELETE FROM membewrs_login
WHERE MEMBERS_ID = 'M-03';
DELETE FROM membewrs_login
WHERE MEMBERS_ID = 'M-04'; 
DELETE FROM membewrs_login
WHERE MEMBERS_ID = 'M-05'; 

DELETE FROM members
WHERE MEMBERS_ID = 'M-02';
DELETE FROM members
WHERE MEMBERS_ID = 'M-03';
DELETE FROM members
WHERE MEMBERS_ID = 'M-04';
DELETE FROM members
WHERE MEMBERS_ID = 'M-05';

