
CREATE TABLE CARS
(
  COMPANY_NAME VARCHAR(50) NOT NULL COMMENT '회사이름',
  CAR_NAME     VARCHAR(50) NOT NULL COMMENT '자동차이름',
  YEAR         VARCHAR(50) NOT NULL COMMENT '연식',
  UNIQUE_ID    VARCHAR(50) NOT NULL COMMENT '유니크 ID',
  PRIMARY KEY (UNIQUE_ID)
) COMMENT '자동차';

CREATE TABLE CARS_OPTIONS
(
  OPTIONS         VARCHAR(50) NOT NULL COMMENT '옵션',
  UNIQUE_ID       VARCHAR(50) NOT NULL COMMENT '유니크 ID',
  CARS_OPTIONS_ID VARCHAR(50) NOT NULL COMMENT '자동차 옵션 ID'
) COMMENT '자동차 옵션';

ALTER TABLE CARS_OPTIONS
  ADD CONSTRAINT FK_CARS_TO_CARS_OPTIONS
    FOREIGN KEY (UNIQUE_ID)
    REFERENCES CARS (UNIQUE_ID);
